---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: bootstrap-archlinux
    image: base/archlinux
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      r: molecule/ansible-lint-rules/
scenario:
  name: archlinux
verifier:
  name: goss
  lint:
    name: yamllint
