---
sudo: required
language: python
services: docker

env:
  - ansible_version="ansible>=2.5,<2.6" distro="alpine-latest"
  - ansible_version="ansible" distro="alpine-latest"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="alpine-latest"
  - ansible_version="ansible>=2.5,<2.6" distro="alpine-edge"
  - ansible_version="ansible" distro="alpine-edge"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="alpine-edge"
  - ansible_version="ansible>=2.5,<2.6" distro="archlinux"
  - ansible_version="ansible" distro="archlinux"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="archlinux"
  - ansible_version="ansible>=2.5,<2.6" distro="centos-6"
  - ansible_version="ansible" distro="centos-6"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="centos-6"
  - ansible_version="ansible>=2.5,<2.6" distro="centos-latest"
  - ansible_version="ansible" distro="centos-latest"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="centos-latest"
  - ansible_version="ansible>=2.5,<2.6" distro="debian-latest"
  - ansible_version="ansible" distro="debian-latest"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="debian-latest"
  - ansible_version="ansible>=2.5,<2.6" distro="debian-stable"
  - ansible_version="ansible" distro="debian-stable"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="debian-stable"
  - ansible_version="ansible>=2.5,<2.6" distro="debian-unstable"
  - ansible_version="ansible" distro="debian-unstable"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="debian-unstable"
  - ansible_version="ansible>=2.5,<2.6" distro="fedora-latest"
  - ansible_version="ansible" distro="fedora-latest"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="fedora-latest"
  - ansible_version="ansible>=2.5,<2.6" distro="fedora-rawhide"
  - ansible_version="ansible" distro="fedora-rawhide"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="fedora-rawhide"
  - ansible_version="ansible>=2.5,<2.6" distro="gentoo"
  - ansible_version="ansible" distro="gentoo"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="gentoo"
  - ansible_version="ansible>=2.5,<2.6" distro="opensuse-leap"
  - ansible_version="ansible" distro="opensuse-leap"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="opensuse-leap"
  - ansible_version="ansible>=2.5,<2.6" distro="opensuse-tumbleweed"
  - ansible_version="ansible" distro="opensuse-tumbleweed"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="opensuse-tumbleweed"
  - ansible_version="ansible>=2.5,<2.6" distro="ubuntu-artful"
  - ansible_version="ansible" distro="ubuntu-artful"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="ubuntu-artful"
  - ansible_version="ansible>=2.5,<2.6" distro="ubuntu-latest"
  - ansible_version="ansible" distro="ubuntu-latest"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="ubuntu-latest"
  - ansible_version="ansible>=2.5,<2.6" distro="ubuntu-devel"
  - ansible_version="ansible" distro="ubuntu-devel"
  - ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="ubuntu-devel"

matrix:
  allow_failures:
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="alpine-latest"
    - env: ansible_version="ansible>=2.5,<2.6" distro="alpine-edge"
    - env: ansible_version="ansible" distro="alpine-edge"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="alpine-edge"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="archlinux"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="centos-6"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="centos-latest"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="debian-latest"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="debian-stable"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="debian-unstable"
    - env: ansible_version="ansible>=2.5,<2.6" distro="debian-unstable"
    - env: ansible_version="ansible" distro="debian-unstable"
    - env: ansible_version="ansible>=2.5,<2.6" distro="fedora-rawhide"
    - env: ansible_version="ansible" distro="fedora-rawhide"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="fedora-rawhide"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="fedora-latest"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="gentoo"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="opensuse-leap"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="opensuse-tumbleweed"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="ubuntu-artful"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="ubuntu-latest"
    - env: ansible_version="ansible>=2.5,<2.6" distro="ubuntu-devel"
    - env: ansible_version="ansible" distro="ubuntu-devel"
    - env: ansible_version="git+https://github.com/ansible/ansible.git@devel" distro="ubuntu-devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install "${ansible_version}"
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "KuGPzSKoDq3x2DRdpGJAZ6Ra0avR7W5mm2smJcKbH7x/Aq4ht1NI+TOFUm0aOVBmT4GdyDjxFOEsWr/bLI5HQ4HL+NpCSFCAEQRDepEafNtrxQ3zY/uz0+2UE/BpVeb/8N8TCnNIsCBoVH6bWP6V6DF0L+phafXT/daBIs8pII4xBlWEdeT/md9QC+yYe54HnlEYNfATzlpE6Q/AkJZlDh1g+5uVnJWNVuO7juMEOI6Eruzj8kXJgpYaQey0i1RhK8UqwADijsLWjgSpEBo9vuZJSBEmAkwIMk/9H2jnWBZxP97Q15iBn5IINhfkL4M2qnP90AxP9uX8yKx3AHxeueTM8OaIRxsHZZA7hTAkP8/iRoMpRUEFxRarZrC9+JrmjYsBfb1Gk2yYCX1tQtAnxVf+U5WUxS4a0uVMI8QhYwgMwno7NSVguG9qiH73EHcPNNDLtNOBtL4R7th/drVx84Kz8HAXVUh2ZxmlzcPejrTixXPx9lsgiaX6pNSqJHay9G0vazZHIRSbg7WdRCW8vx9zoNe4FSQEBV+J4xcwafRe7hDMX4YimKl8rU9etQUQPEhdDCTBpQ8GUHDPpYIGdv+FfKdFCKKrSfEbtiY4SEHP+Bl+0eul8iooNVCqtwYVKk/GBx1VxpYVsiJYsj16wMQvyOi3jFoYB9PYBSFN43s="
  email: false
