---
sudo: required
language: python
services: docker

global:
  - ansible_previous="ansible>=2.5,<2.6"
  - ansible_current="ansible"
  - ansible_future="git+https://github.com/ansible/ansible.git@devel"

env:
 - distro="alpine-latest" ansible_version="${ansible_previous}"
 - distro="alpine-latest" ansible_version="${ansible_current}"
 - distro="alpine-latest" ansible_version="${ansible_future}"
 - distro="alpine-egde" ansible_version="${ansible_previous}"
 - distro="alpine-egde" ansible_version="${ansible_current}"
 - distro="alpine-egde" ansible_version="${ansible_future}"
 - distro="archlinux" ansible_version="${ansible_previous}"
 - distro="archlinux" ansible_version="${ansible_current}"
 - distro="archlinux" ansible_version="${ansible_future}"
 - distro="centos-6" ansible_version="${ansible_previous}"
 - distro="centos-6" ansible_version="${ansible_current}"
 - distro="centos-6" ansible_version="${ansible_future}"
 - distro="centos-latest" ansible_version="${ansible_previous}"
 - distro="centos-latest" ansible_version="${ansible_current}"
 - distro="centos-latest" ansible_version="${ansible_future}"
 - distro="debian-latest" ansible_version="${ansible_previous}"
 - distro="debian-latest" ansible_version="${ansible_current}"
 - distro="debian-latest" ansible_version="${ansible_future}"
 - distro="debian-stable" ansible_version="${ansible_previous}"
 - distro="debian-stable" ansible_version="${ansible_current}"
 - distro="debian-stable" ansible_version="${ansible_future}"
 - distro="debian-unstable" ansible_version="${ansible_previous}"
 - distro="debian-unstable" ansible_version="${ansible_current}"
 - distro="debian-unstable" ansible_version="${ansible_future}"
 - distro="fedora-latest" ansible_version="${ansible_previous}"
 - distro="fedora-latest" ansible_version="${ansible_current}"
 - distro="fedora-latest" ansible_version="${ansible_future}"
 - distro="fedora-rawhide" ansible_version="${ansible_previous}"
 - distro="fedora-rawhide" ansible_version="${ansible_current}"
 - distro="fedora-rawhide" ansible_version="${ansible_future}"
 - distro="gentoo" ansible_version="${ansible_previous}"
 - distro="gentoo" ansible_version="${ansible_current}"
 - distro="gentoo" ansible_version="${ansible_future}"
 - distro="opensuse-leap" ansible_version="${ansible_previous}"
 - distro="opensuse-leap" ansible_version="${ansible_current}"
 - distro="opensuse-leap" ansible_version="${ansible_future}"
 - distro="opensuse-tumbleweed" ansible_version="${ansible_previous}"
 - distro="opensuse-tumbleweed" ansible_version="${ansible_current}"
 - distro="opensuse-tumbleweed" ansible_version="${ansible_future}"
 - distro="ubuntu-artful" ansible_version="${ansible_previous}"
 - distro="ubuntu-artful" ansible_version="${ansible_current}"
 - distro="ubuntu-artful" ansible_version="${ansible_future}"
 - distro="ubuntu-latest" ansible_version="${ansible_previous}"
 - distro="ubuntu-latest" ansible_version="${ansible_current}"
 - distro="ubuntu-latest" ansible_version="${ansible_future}"
 - distro="ubuntu-devel" ansible_version="${ansible_previous}"
 - distro="ubuntu-devel" ansible_version="${ansible_current}"
 - distro="ubuntu-devel" ansible_version="${ansible_future}"

matrix:
  allow_failures:
    - distro="alpine-latest" ansible_version="${ansible_future}"


cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install "${ansible_version}"
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "KuGPzSKoDq3x2DRdpGJAZ6Ra0avR7W5mm2smJcKbH7x/Aq4ht1NI+TOFUm0aOVBmT4GdyDjxFOEsWr/bLI5HQ4HL+NpCSFCAEQRDepEafNtrxQ3zY/uz0+2UE/BpVeb/8N8TCnNIsCBoVH6bWP6V6DF0L+phafXT/daBIs8pII4xBlWEdeT/md9QC+yYe54HnlEYNfATzlpE6Q/AkJZlDh1g+5uVnJWNVuO7juMEOI6Eruzj8kXJgpYaQey0i1RhK8UqwADijsLWjgSpEBo9vuZJSBEmAkwIMk/9H2jnWBZxP97Q15iBn5IINhfkL4M2qnP90AxP9uX8yKx3AHxeueTM8OaIRxsHZZA7hTAkP8/iRoMpRUEFxRarZrC9+JrmjYsBfb1Gk2yYCX1tQtAnxVf+U5WUxS4a0uVMI8QhYwgMwno7NSVguG9qiH73EHcPNNDLtNOBtL4R7th/drVx84Kz8HAXVUh2ZxmlzcPejrTixXPx9lsgiaX6pNSqJHay9G0vazZHIRSbg7WdRCW8vx9zoNe4FSQEBV+J4xcwafRe7hDMX4YimKl8rU9etQUQPEhdDCTBpQ8GUHDPpYIGdv+FfKdFCKKrSfEbtiY4SEHP+Bl+0eul8iooNVCqtwYVKk/GBx1VxpYVsiJYsj16wMQvyOi3jFoYB9PYBSFN43s="
  email: false
