---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: bootstrap-ubuntu-devel
    image: ubuntu:devel
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      r: molecule/ansible-lint-rules/
scenario:
  name: ubuntu-devel
verifier:
  name: goss
  lint:
    name: yamllint
