---
# vars file for bootstrap
bootstrap_assert_rules:
  - assertion: bootstrap_user is defined
    message: the bootstrap_user must be defined
  - assertion: bootstrap_wait_for_host is defined
    message: the bootstrap_wait_for_host must be defined
  - assertion: bootstrap_wait_for_host | bool
    message: the bootstrap_wait_for_host variable must be a boolean (yes/true/1 or no/false/0)

bootstrap_minimal_packages: "python sudo"

bootstrap_stable_packages:
  - libselinux-python
  - libsemanage-python
  - polkit
  - python-devel
  - python-simplejson
  - python2-dnf

bootstrap_preview_packages:
  - lvm2
  - tar
  - unzip
  - gzip
  - policycoreutils-python

bootstrap_apk_packages: python sudo

bootstrap_apt_packages: python sudo

bootstrap_dnf_packages: python2 python2-dnf sudo

bootstrap_emerge_packages: python sudo gentoolkit

bootstrap_pacman_packages: python sudo

bootstrap_yum_packages: python2 sudo

bootstrap_zypper_packages: python python-xml sudo
