---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: bootstrap-opensuse-tumbleweed
    image: opensuse:tumbleweed
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      r: molecule/ansible-lint-rules/
scenario:
  name: opensuse-tumbleweed
verifier:
  name: goss
  lint:
    name: yamllint
